services:
  server:
    image: searchle/server:latest
    build:
      context: server
      dockerfile: webapi.Dockerfile
    ports:
      - 8080:80
    environment:
      - Searchle:DictionaryConnectionString=${DICTIONARY_CNN_STRING}
      - Searchle:RootKey=${ROOT_KEY}
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}